version: '3.11'

services:
  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - redis
    restart: unless-stopped


  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped


  celery:
    build: .
    command: celery -A ecommerce_store.celery worker -l info
    restart: unless-stopped
    depends_on:
      - web
      - redis
