# Generated by Django 5.0.6 on 2024-05-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
