# Generated by Django 5.0.6 on 2024-05-31 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_image_images_alter_comment_star_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
